name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-image:latest .

      - name: Save image to tar.gz
        run: docker save my-image:latest | gzip > my-image.tar.gz

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-docker-image
          path: my-image.tar.gz
